CC = g++
LIB = ar 
CPPFLAGS = -fPIC `pkg-config --cflags opencv4` -I../inc/
LDFLAGS = `pkg-config --libs opencv4` -L./ -lISCSDKLibvm200 -lISCLibvm -lISCUSBLibvm -lftdi1

all: libbasic.a libx3.a

OBJS = libbasic.o libx3.o
SRCS = $(OBJS:.o=.cpp)

libbasic.a: libbasic.o 
	$(LIB) rcs $@ $^

libx3.a:  libx3.o
	$(LIB) rcs $@ $^

%.o: %.c
	$(CC) $(CPPFLAG) $(INC) -c $<

%.o: %.cpp
	$(CC) $(CPPFLAGS) $(INC) -c $< 

clean:
	rm -f *.o *.*~ *~ *.un~

depend:
	makedepend -- $(CPPFLAGS) -- $(SRCS)

# DO NOT DELETE

libbasic.o: /usr/include/stdio.h /usr/include/stdlib.h /usr/include/string.h
libbasic.o: /usr/include/unistd.h /usr/include/features.h
libbasic.o: /usr/include/stdc-predef.h /usr/include/linux/types.h
libbasic.o: /usr/include/linux/posix_types.h /usr/include/linux/stddef.h
libbasic.o: /usr/local/include/opencv4/opencv2/core/core.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/cvdef.h
libbasic.o: /usr/local/include/opencv4/opencv2/core/version.hpp
libbasic.o: /usr/include/limits.h
libbasic.o: /usr/local/include/opencv4/opencv2/core/hal/interface.h
libbasic.o: /usr/include/stdint.h
libbasic.o: /usr/local/include/opencv4/opencv2/core/cv_cpu_dispatch.h
libbasic.o: /usr/local/include/opencv4/opencv2/core/fast_math.hpp
libbasic.o: /usr/include/math.h
libbasic.o: /usr/local/include/opencv4/opencv2/core/base.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/opencv_modules.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/cvstd.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/neon_utils.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/vsx_utils.hpp
libbasic.o: /usr/include/assert.h
libbasic.o: /usr/local/include/opencv4/opencv2/core/check.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/traits.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/matx.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/saturate.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/types.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/mat.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/bufferpool.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/mat.inl.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/persistence.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/operations.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/cvstd.inl.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/utility.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/optim.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/ovx.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/core/cvdef.h
libbasic.o: /usr/local/include/opencv4/opencv2/highgui/highgui.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/highgui.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/imgcodecs.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/videoio.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/imgproc.hpp
libbasic.o: /usr/local/include/opencv4/opencv2/./imgproc/segmentation.hpp
libbasic.o: ../inc/ISCSDKLib.h ../inc/libbasic.h
libx3.o: /usr/include/stdio.h /usr/include/stdlib.h /usr/include/string.h
libx3.o: /usr/include/unistd.h /usr/include/features.h
libx3.o: /usr/include/stdc-predef.h
libx3.o: /usr/local/include/opencv4/opencv2/core/core.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/cvdef.h
libx3.o: /usr/local/include/opencv4/opencv2/core/version.hpp
libx3.o: /usr/include/limits.h
libx3.o: /usr/local/include/opencv4/opencv2/core/hal/interface.h
libx3.o: /usr/include/stdint.h
libx3.o: /usr/local/include/opencv4/opencv2/core/cv_cpu_dispatch.h
libx3.o: /usr/local/include/opencv4/opencv2/core/fast_math.hpp
libx3.o: /usr/include/math.h /usr/local/include/opencv4/opencv2/core/base.hpp
libx3.o: /usr/local/include/opencv4/opencv2/opencv_modules.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/cvstd.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/neon_utils.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/vsx_utils.hpp
libx3.o: /usr/include/assert.h
libx3.o: /usr/local/include/opencv4/opencv2/core/check.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/traits.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/matx.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/saturate.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/types.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/mat.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/bufferpool.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/mat.inl.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/persistence.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/operations.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/cvstd.inl.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/utility.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/optim.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/ovx.hpp
libx3.o: /usr/local/include/opencv4/opencv2/core/cvdef.h
libx3.o: /usr/local/include/opencv4/opencv2/highgui/highgui.hpp
libx3.o: /usr/local/include/opencv4/opencv2/highgui.hpp
libx3.o: /usr/local/include/opencv4/opencv2/imgcodecs.hpp
libx3.o: /usr/local/include/opencv4/opencv2/videoio.hpp
libx3.o: /usr/local/include/opencv4/opencv2/imgproc.hpp
libx3.o: /usr/local/include/opencv4/opencv2/./imgproc/segmentation.hpp
libx3.o: ../inc/libx3.h
