all:
	cd ./00_getparam/main && make all
	cd ./01_getpic/main && make all
	cd ./02_getvpic/main && make all
	cd ./03_color/main && make all
	cd ./04_impose/main && make all
	cd ./05_exposure/main && make all
	cd ./06_distance/main && make all
	cd ./07_hscale/main && make all
	cd ./08_histgram/main && make all
	cd ./09_freeze/main && make all
	cd ./10_avi/main && make all
	cd ./11_edge/main && make all
	cd ./12_hough/main && make all
	cd ./13_bthresh/main && make all
	cd ./14_movdet/main && make all
	cd ./15_movdet_by_depth/main && make all
clean:
	cd ./00_getparam/main && make clean
	cd ./01_getpic/main && make clean
	cd ./02_getvpic/main && make clean
	cd ./03_color/main && make clean
	cd ./04_impose/main && make clean
	cd ./05_exposure/main && make clean
	cd ./06_distance/main && make clean
	cd ./07_hscale/main && make clean
	cd ./08_histgram/main && make clean
	cd ./09_freeze/main && make clean
	cd ./10_avi/main && make clean
	cd ./11_edge/main && make clean
	cd ./12_hough/main && make clean
	cd ./13_bthresh/main && make clean
	cd ./14_movdet/main && make clean
	cd ./15_movdet_by_depth/main && make clean
depend:
	cd ./00_getparam/main && make depend
	cd ./01_getpic/main && make depend
	cd ./02_getvpic/main && make depend
	cd ./03_color/main && make depend
	cd ./04_impose/main && make depend
	cd ./05_exposure/main && make depend
	cd ./06_distance/main && make depend
	cd ./07_hscale/main && make depend
	cd ./08_histgram/main && make depend
	cd ./09_freeze/main && make depend
	cd ./10_avi/main && make depend
	cd ./11_edge/main && make depend
	cd ./12_hough/main && make depend
	cd ./13_bthresh/main && make depend
	cd ./14_movdet/main && make depend
	cd ./15_movdet_by_depth/main && make depend
update:
	cp ./common/* ./00_getparam/main
	cp ./common/* ./01_getpic/main
	cp ./common/* ./02_getvpic/main
	cp ./common/* ./03_color/main
	cp ./common/* ./04_impose/main
	cp ./common/* ./05_exposure/main
	cp ./common/* ./06_distance/main
	cp ./common/* ./07_hscale/main
	cp ./common/* ./08_histgram/main
	cp ./common/* ./09_freeze/main
	cp ./common/* ./10_avi/main
	cp ./common/* ./11_edge/main
	cp ./common/* ./12_hough/main
	cp ./common/* ./13_bthresh/main
	cp ./common/* ./14_movdet/main
	cp ./common/* ./15_movdet_by_depth/main

